language: node_js
node_js:
  - "7"

sudo: true

install:
  - npm install

script:
  - bsb -make-world
  - npm run webpack

cache:
  directories:
      - node_modules

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master